server:
  port: 8091
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3309/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
   init:
    mode: always
  config:
    import: "optional:configserver:http://configserver-ms:8071/"
#  rabbitmq:
#    host: "rabbitmq"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"